### ISSUE TITLE
Background is light, not dark

### ISSUE THREAD

**Issue by mcamiano** [jdan/cleaver-retro#2]
When processed by v0.8.2 and viewed in Chrome, the theme results in a black-on-white appearance rather than the depicted style.  It seems that the default css for `.slide` is not being set by this theme, so it inherits the default.

**Comment by mattcoker** [comment]
Same issue here

**Comment by jdan** [comment]
Hey @mcamiano @mattcoker I'll give this a look today - sorry! Looks like there's a weird bug in themes.

**Comment by mattcoker** [comment]
@jdan No worries, found the issue. Not sure if this is a good solution, or perhaps there's something further upstream to be fixed. Either way, this fixes it for me. #3

**Comment by mattcoker** [comment]
Also, I don't have time to check and make sure the rest of the styling looks right, so there may be additional changes necessary.

**Comment by jdan** [comment]
Closed via #3 - thanks for looking into (and fixing!) @mattcoker.

@mcamiano Lemme know if things are still acting strange.
